apiVersion: apps/v1
kind: Deployment
metadata:
  name: superliga-dashboard
  namespace: {{namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superliga-dashboard
  template:
    metadata:
      labels:
        app: superliga-dashboard
    spec:
      containers:
        - name: superliga-dashboard
          image: {{image}}
          ports:
            - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: superliga-dashboard
  namespace: {{namespace}}
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: {{nodePort}}
  selector:
    app: superliga-dashboard

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: superliga-dashboard-ingress
  namespace: {{namespace}}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: superliga-dashboard
                port:
                  number: 5000
