name: CI/CD Pipeline

on:
  push:
    branches:
      - qa
      - prd

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: talesvalcacer/superliga-dashboard

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ env.IMAGE_NAME }}:${{ github.ref_name }} .
        docker push ${{ env.IMAGE_NAME }}:${{ github.ref_name }}

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.30.0'

    - name: Configure kubeconfig for QA
      if: github.ref_name == 'qa'
      run: echo "${{ secrets.KUBECONFIG_QA }}" > ~/.kube/config

    - name: Configure kubeconfig for PRD
      if: github.ref_name == 'prd'
      run: echo "${{ secrets.KUBECONFIG_PRD }}" > ~/.kube/config

    - name: Deploy to Kubernetes (QA)
      if: github.ref_name == 'qa'
      run: |
        sed -e "s|{{namespace}}|qa|g" -e "s|{{image}}|${{ env.IMAGE_NAME }}:${{ github.ref_name }}|g" app.yaml | kubectl apply -f -

    - name: Deploy to Kubernetes (PRD)
      if: github.ref_name == 'prd'
      run: |
        sed -e "s|{{namespace}}|prd|g" -e "s|{{image}}|${{ env.IMAGE_NAME }}:${{ github.ref_name }}|g" app.yaml | kubectl apply -f -
